/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n    query fetchUserLoggedIn {\n        fetchUserLoggedIn {\n            _id\n            email\n            name\n            userPoint {\n                amount\n            }\n        }\n    }\n": typeof types.FetchUserLoggedInDocument,
    "\n    query fetchTravelproduct($travelproductId: ID!) {\n        fetchTravelproduct(travelproductId: $travelproductId) {\n            _id\n            name\n            remarks\n            contents\n            price\n            tags\n            images\n            pickedCount\n            travelproductAddress {\n                zipcode\n                address\n                addressDetail\n                lat\n                lng\n            }\n            buyer {\n                _id\n                email\n                name\n            }\n            seller {\n                _id\n                email\n                name\n            }\n            soldAt\n            createdAt\n            updatedAt\n        }\n    }\n": typeof types.FetchTravelproductDocument,
    "\n    mutation createPointTransactionOfLoading($paymentId: ID!) {\n        createPointTransactionOfLoading(paymentId: $paymentId) {\n            _id\n            amount\n            status\n            statusDetail\n            createdAt\n            updatedAt\n        }\n    }\n": typeof types.CreatePointTransactionOfLoadingDocument,
    "\n    query fetchPointTransactions($search: String, $page: Int) {\n        fetchPointTransactions(search: $search, page: $page) {\n            _id\n            createdAt\n            status\n            amount\n            balance\n        }\n    }\n": typeof types.FetchPointTransactionsDocument,
    "\n    query fetchPointTransactionsOfLoading($search: String, $page: Int) {\n        fetchPointTransactionsOfLoading(search: $search, page: $page) {\n            createdAt\n            impUid\n            amount\n            balance\n        }\n    }\n": typeof types.FetchPointTransactionsOfLoadingDocument,
    "\n    mutation logoutUser {\n        logoutUser\n    }\n": typeof types.LogoutUserDocument,
    "\n    mutation restoreAccessToken {\n        restoreAccessToken {\n            accessToken\n        }\n    }\n": typeof types.RestoreAccessTokenDocument,
    "\n    mutation deleteBoardComment($password: String, $boardCommentId: ID!) {\n        deleteBoardComment(password: $password, boardCommentId: $boardCommentId)\n    }\n": typeof types.DeleteBoardCommentDocument,
    "\n    query fetchBoardComments($boardId: ID!, $page: Int) {\n        fetchBoardComments(boardId: $boardId, page: $page) {\n            _id\n            writer\n            contents\n            rating\n            createdAt\n            user {\n                _id\n            }\n        }\n    }\n": typeof types.FetchBoardCommentsDocument,
    "\n    mutation createBoardComment($createBoardCommentInput: CreateBoardCommentInput!, $boardId: ID!) {\n        createBoardComment(createBoardCommentInput: $createBoardCommentInput, boardId: $boardId) {\n            _id\n            writer\n            contents\n            rating\n        }\n    }\n": typeof types.CreateBoardCommentDocument,
    "\n    mutation updateBoardComment(\n        $updateBoardCommentInput: UpdateBoardCommentInput!\n        $password: String\n        $boardCommentId: ID!\n    ) {\n        updateBoardComment(\n            updateBoardCommentInput: $updateBoardCommentInput\n            password: $password\n            boardCommentId: $boardCommentId\n        ) {\n            _id\n            writer\n            contents\n            rating\n            updatedAt\n        }\n    }\n": typeof types.UpdateBoardCommentDocument,
    "\n    query fetchBoard($boardId: ID!) {\n        fetchBoard(boardId: $boardId) {\n            _id\n            writer\n            title\n            contents\n            likeCount\n            dislikeCount\n            createdAt\n            youtubeUrl\n            boardAddress {\n                zipcode\n                address\n                addressDetail\n            }\n            images\n            createdAt\n            user {\n                _id\n            }\n        }\n    }\n": typeof types.FetchBoardDocument,
    "\n    mutation likeBoard($boardId: ID!) {\n        likeBoard(boardId: $boardId)\n    }\n": typeof types.LikeBoardDocument,
    "\n    mutation dislikeBoard($boardId: ID!) {\n        dislikeBoard(boardId: $boardId)\n    }\n": typeof types.DislikeBoardDocument,
    "\n    query fetchBoards($page: Int, $search: String, $endDate: DateTime, $startDate: DateTime) {\n        fetchBoards(page: $page, search: $search, endDate: $endDate, startDate: $startDate) {\n            _id\n            writer\n            title\n            contents\n            youtubeUrl\n            likeCount\n            dislikeCount\n            boardAddress {\n                zipcode\n                address\n                addressDetail\n            }\n            createdAt\n            images\n        }\n    }\n": typeof types.FetchBoardsDocument,
    "\n    mutation deleteBoard($boardId: ID!) {\n        deleteBoard(boardId: $boardId)\n    }\n": typeof types.DeleteBoardDocument,
    "\n    query fetchBoardsCount($search: String, $startDate: DateTime, $endDate: DateTime) {\n        fetchBoardsCount(search: $search, startDate: $startDate, endDate: $endDate)\n    }\n": typeof types.FetchBoardsCountDocument,
    "\n    mutation createBoard($createBoardInput: CreateBoardInput!) {\n        createBoard(createBoardInput: $createBoardInput) {\n            _id\n            writer\n            title\n            contents\n            likeCount\n            dislikeCount\n            createdAt\n            youtubeUrl\n            boardAddress {\n                zipcode\n                address\n                addressDetail\n            }\n            images\n            createdAt\n        }\n    }\n": typeof types.CreateBoardDocument,
    "\n    mutation updateBoard($boardId: ID!, $password: String, $updateBoardInput: UpdateBoardInput!) {\n        updateBoard(boardId: $boardId, password: $password, updateBoardInput: $updateBoardInput) {\n            _id\n            writer\n            title\n            contents\n            likeCount\n            dislikeCount\n            createdAt\n            youtubeUrl\n            boardAddress {\n                zipcode\n                address\n                addressDetail\n            }\n            images\n            createdAt\n        }\n    }\n": typeof types.UpdateBoardDocument,
    "\n    mutation uploadFile($file: Upload!) {\n        uploadFile(file: $file) {\n            _id\n            url\n            size\n        }\n    }\n": typeof types.UploadFileDocument,
    "\n    query fetchTravelproductsIPicked($search: String, $page: Int) {\n        fetchTravelproductsIPicked(search: $search, page: $page) {\n            _id\n            name\n            price\n            seller {\n                name\n            }\n            createdAt\n        }\n    }\n": typeof types.FetchTravelproductsIPickedDocument,
    "\n    query fetchTravelproductsISold($page: Int) {\n        fetchTravelproductsISold(page: $page) {\n            _id\n            name\n            price\n            createdAt\n            soldAt\n        }\n    }\n": typeof types.FetchTravelproductsISoldDocument,
    "\n    mutation resetUserPassword($password: String!) {\n        resetUserPassword(password: $password)\n    }\n": typeof types.ResetUserPasswordDocument,
    "\n    query fetchPointTransactionsOfBuying($search: String, $page: Int) {\n        fetchPointTransactionsOfBuying(search: $search, page: $page) {\n            createdAt\n            travelproduct {\n                name\n                # seller {\n                #     name\n                # }\n            }\n            amount\n            balance\n        }\n    }\n": typeof types.FetchPointTransactionsOfBuyingDocument,
    "\n    query fetchPointTransactionsOfSelling($search: String, $page: Int) {\n        fetchPointTransactionsOfSelling(search: $search, page: $page) {\n            createdAt\n            travelproduct {\n                name\n            }\n            amount\n            balance\n        }\n    }\n": typeof types.FetchPointTransactionsOfSellingDocument,
    "\n    query fetchTravelproductsOfTheBest {\n        fetchTravelproductsOfTheBest {\n            _id\n            name\n            contents\n            price\n            pickedCount\n            images\n            soldAt\n        }\n    }\n": typeof types.FetchTravelproductsOfTheBestDocument,
    "\n    mutation toggleTravelproductPick($travelproductId: ID!) {\n        toggleTravelproductPick(travelproductId: $travelproductId)\n    }\n": typeof types.ToggleTravelproductPickDocument,
    "\n    mutation createPointTransactionOfBuyingAndSelling($useritemId: ID!) {\n        createPointTransactionOfBuyingAndSelling(useritemId: $useritemId) {\n            _id\n            name\n            remarks\n            contents\n            price\n            tags\n            images\n            pickedCount\n            travelproductAddress {\n                zipcode\n                address\n                addressDetail\n                lat\n                lng\n                # createdAt\n                # updatedAt\n            }\n            createdAt\n            updatedAt\n        }\n    }\n": typeof types.CreatePointTransactionOfBuyingAndSellingDocument,
    "\n    mutation deleteTravelproduct($travelproductId: ID!) {\n        deleteTravelproduct(travelproductId: $travelproductId)\n    }\n": typeof types.DeleteTravelproductDocument,
    "\n    mutation deleteTravelproductQuestion($travelproductQuestionId: ID!) {\n        deleteTravelproductQuestion(travelproductQuestionId: $travelproductQuestionId)\n    }\n": typeof types.DeleteTravelproductQuestionDocument,
    "\n    query fetchTravelproductQuestions($travelproductId: ID!) {\n        fetchTravelproductQuestions(travelproductId: $travelproductId) {\n            _id\n            contents\n            user {\n                _id\n                email\n                name\n                createdAt\n                updatedAt\n            }\n            createdAt\n            updatedAt\n        }\n    }\n": typeof types.FetchTravelproductQuestionsDocument,
    "\n    mutation deleteTravelproductQuestionAnswer($travelproductQuestionAnswerId: ID!) {\n        deleteTravelproductQuestionAnswer(\n            travelproductQuestionAnswerId: $travelproductQuestionAnswerId\n        )\n    }\n": typeof types.DeleteTravelproductQuestionAnswerDocument,
    "\n    query fetchTravelproductQuestionAnswers($travelproductQuestionId: ID!) {\n        fetchTravelproductQuestionAnswers(travelproductQuestionId: $travelproductQuestionId) {\n            _id\n            contents\n            user {\n                _id\n                name\n                createdAt\n                updatedAt\n            }\n            createdAt\n            updatedAt\n        }\n    }\n": typeof types.FetchTravelproductQuestionAnswersDocument,
    "\n    mutation createTravelproductQuestion(\n        $travelproductId: ID!\n        $createTravelproductQuestionInput: CreateTravelproductQuestionInput!\n    ) {\n        createTravelproductQuestion(\n            travelproductId: $travelproductId\n            createTravelproductQuestionInput: $createTravelproductQuestionInput\n        ) {\n            _id\n            contents\n\n            user {\n                _id\n                email\n                name\n                createdAt\n                updatedAt\n            }\n            createdAt\n            updatedAt\n        }\n    }\n": typeof types.CreateTravelproductQuestionDocument,
    "\n    query fetchTravelproductQuestions($travelproductId: ID!) {\n        fetchTravelproductQuestions(travelproductId: $travelproductId) {\n            _id\n            contents\n\n            user {\n                _id\n                email\n                name\n                createdAt\n                updatedAt\n            }\n            createdAt\n            updatedAt\n        }\n    }\n": typeof types.FetchTravelproductQuestionsDocument,
    "\n    mutation createTravelproductQuestionAnswer(\n        $travelproductQuestionId: ID!\n        $createTravelproductQuestionAnswerInput: CreateTravelproductQuestionAnswerInput!\n    ) {\n        createTravelproductQuestionAnswer(\n            createTravelproductQuestionAnswerInput: $createTravelproductQuestionAnswerInput\n            travelproductQuestionId: $travelproductQuestionId\n        ) {\n            _id\n            contents\n\n            user {\n                _id\n                email\n                name\n                createdAt\n                updatedAt\n            }\n            createdAt\n            updatedAt\n        }\n    }\n": typeof types.CreateTravelproductQuestionAnswerDocument,
    "\n    mutation updateTravelproductQuestion(\n        $updateTravelproductQuestionInput: UpdateTravelproductQuestionInput!\n        $travelproductQuestionId: ID!\n    ) {\n        updateTravelproductQuestion(\n            updateTravelproductQuestionInput: $updateTravelproductQuestionInput\n            travelproductQuestionId: $travelproductQuestionId\n        ) {\n            _id\n            contents\n            user {\n                _id\n                email\n                name\n                createdAt\n                updatedAt\n            }\n            createdAt\n            updatedAt\n        }\n    }\n": typeof types.UpdateTravelproductQuestionDocument,
    "\n    mutation updateTravelproductQuestionAnswer(\n        $travelproductQuestionAnswerId: ID!\n        $updateTravelproductQuestionAnswerInput: UpdateTravelproductQuestionAnswerInput!\n    ) {\n        updateTravelproductQuestionAnswer(\n            travelproductQuestionAnswerId: $travelproductQuestionAnswerId\n            updateTravelproductQuestionAnswerInput: $updateTravelproductQuestionAnswerInput\n        ) {\n            _id\n            contents\n            user {\n                _id\n                name\n            }\n            createdAt\n            updatedAt\n        }\n    }\n": typeof types.UpdateTravelproductQuestionAnswerDocument,
    "\n    query fetchTravelproducts($isSoldout: Boolean, $page: Int, $search: String) {\n        fetchTravelproducts(isSoldout: $isSoldout, page: $page, search: $search) {\n            _id\n            name\n            remarks\n            contents\n            price\n            tags\n            images\n            pickedCount\n            travelproductAddress {\n                zipcode\n                address\n                addressDetail\n                lat\n                lng\n            }\n            seller {\n                _id\n                email\n                name\n            }\n            soldAt\n            createdAt\n            updatedAt\n        }\n    }\n": typeof types.FetchTravelproductsDocument,
    "\n    mutation createTravelproduct($createTravelproductInput: CreateTravelproductInput!) {\n        createTravelproduct(createTravelproductInput: $createTravelproductInput) {\n            _id\n            name\n            remarks\n            contents\n            price\n            tags\n            images\n            pickedCount\n            travelproductAddress {\n                zipcode\n                address\n                addressDetail\n                lat\n                lng\n            }\n            buyer {\n                _id\n                email\n                name\n            }\n            seller {\n                _id\n                email\n                name\n            }\n            soldAt\n            createdAt\n            updatedAt\n        }\n    }\n": typeof types.CreateTravelproductDocument,
    "\n    mutation updateTravelproduct(\n        $updateTravelproductInput: UpdateTravelproductInput!\n        $travelproductId: ID!\n    ) {\n        updateTravelproduct(\n            updateTravelproductInput: $updateTravelproductInput\n            travelproductId: $travelproductId\n        ) {\n            _id\n            name\n            remarks\n            contents\n            price\n            tags\n            images\n            pickedCount\n            travelproductAddress {\n                zipcode\n                address\n                addressDetail\n                lat\n                lng\n            }\n            buyer {\n                _id\n                email\n                name\n            }\n            seller {\n                _id\n                email\n                name\n            }\n            soldAt\n            createdAt\n            updatedAt\n        }\n    }\n": typeof types.UpdateTravelproductDocument,
    "\n    mutation loginUser($email: String!, $password: String!) {\n        loginUser(password: $password, email: $email) {\n            accessToken\n        }\n    }\n": typeof types.LoginUserDocument,
    "\n    mutation createUser($email: String!, $password: String!, $name: String!) {\n        createUser(createUserInput: { email: $email, password: $password, name: $name }) {\n            _id\n            email\n            name\n            picture\n            userPoint {\n                amount\n            }\n            createdAt\n        }\n    }\n": typeof types.CreateUserDocument,
};
const documents: Documents = {
    "\n    query fetchUserLoggedIn {\n        fetchUserLoggedIn {\n            _id\n            email\n            name\n            userPoint {\n                amount\n            }\n        }\n    }\n": types.FetchUserLoggedInDocument,
    "\n    query fetchTravelproduct($travelproductId: ID!) {\n        fetchTravelproduct(travelproductId: $travelproductId) {\n            _id\n            name\n            remarks\n            contents\n            price\n            tags\n            images\n            pickedCount\n            travelproductAddress {\n                zipcode\n                address\n                addressDetail\n                lat\n                lng\n            }\n            buyer {\n                _id\n                email\n                name\n            }\n            seller {\n                _id\n                email\n                name\n            }\n            soldAt\n            createdAt\n            updatedAt\n        }\n    }\n": types.FetchTravelproductDocument,
    "\n    mutation createPointTransactionOfLoading($paymentId: ID!) {\n        createPointTransactionOfLoading(paymentId: $paymentId) {\n            _id\n            amount\n            status\n            statusDetail\n            createdAt\n            updatedAt\n        }\n    }\n": types.CreatePointTransactionOfLoadingDocument,
    "\n    query fetchPointTransactions($search: String, $page: Int) {\n        fetchPointTransactions(search: $search, page: $page) {\n            _id\n            createdAt\n            status\n            amount\n            balance\n        }\n    }\n": types.FetchPointTransactionsDocument,
    "\n    query fetchPointTransactionsOfLoading($search: String, $page: Int) {\n        fetchPointTransactionsOfLoading(search: $search, page: $page) {\n            createdAt\n            impUid\n            amount\n            balance\n        }\n    }\n": types.FetchPointTransactionsOfLoadingDocument,
    "\n    mutation logoutUser {\n        logoutUser\n    }\n": types.LogoutUserDocument,
    "\n    mutation restoreAccessToken {\n        restoreAccessToken {\n            accessToken\n        }\n    }\n": types.RestoreAccessTokenDocument,
    "\n    mutation deleteBoardComment($password: String, $boardCommentId: ID!) {\n        deleteBoardComment(password: $password, boardCommentId: $boardCommentId)\n    }\n": types.DeleteBoardCommentDocument,
    "\n    query fetchBoardComments($boardId: ID!, $page: Int) {\n        fetchBoardComments(boardId: $boardId, page: $page) {\n            _id\n            writer\n            contents\n            rating\n            createdAt\n            user {\n                _id\n            }\n        }\n    }\n": types.FetchBoardCommentsDocument,
    "\n    mutation createBoardComment($createBoardCommentInput: CreateBoardCommentInput!, $boardId: ID!) {\n        createBoardComment(createBoardCommentInput: $createBoardCommentInput, boardId: $boardId) {\n            _id\n            writer\n            contents\n            rating\n        }\n    }\n": types.CreateBoardCommentDocument,
    "\n    mutation updateBoardComment(\n        $updateBoardCommentInput: UpdateBoardCommentInput!\n        $password: String\n        $boardCommentId: ID!\n    ) {\n        updateBoardComment(\n            updateBoardCommentInput: $updateBoardCommentInput\n            password: $password\n            boardCommentId: $boardCommentId\n        ) {\n            _id\n            writer\n            contents\n            rating\n            updatedAt\n        }\n    }\n": types.UpdateBoardCommentDocument,
    "\n    query fetchBoard($boardId: ID!) {\n        fetchBoard(boardId: $boardId) {\n            _id\n            writer\n            title\n            contents\n            likeCount\n            dislikeCount\n            createdAt\n            youtubeUrl\n            boardAddress {\n                zipcode\n                address\n                addressDetail\n            }\n            images\n            createdAt\n            user {\n                _id\n            }\n        }\n    }\n": types.FetchBoardDocument,
    "\n    mutation likeBoard($boardId: ID!) {\n        likeBoard(boardId: $boardId)\n    }\n": types.LikeBoardDocument,
    "\n    mutation dislikeBoard($boardId: ID!) {\n        dislikeBoard(boardId: $boardId)\n    }\n": types.DislikeBoardDocument,
    "\n    query fetchBoards($page: Int, $search: String, $endDate: DateTime, $startDate: DateTime) {\n        fetchBoards(page: $page, search: $search, endDate: $endDate, startDate: $startDate) {\n            _id\n            writer\n            title\n            contents\n            youtubeUrl\n            likeCount\n            dislikeCount\n            boardAddress {\n                zipcode\n                address\n                addressDetail\n            }\n            createdAt\n            images\n        }\n    }\n": types.FetchBoardsDocument,
    "\n    mutation deleteBoard($boardId: ID!) {\n        deleteBoard(boardId: $boardId)\n    }\n": types.DeleteBoardDocument,
    "\n    query fetchBoardsCount($search: String, $startDate: DateTime, $endDate: DateTime) {\n        fetchBoardsCount(search: $search, startDate: $startDate, endDate: $endDate)\n    }\n": types.FetchBoardsCountDocument,
    "\n    mutation createBoard($createBoardInput: CreateBoardInput!) {\n        createBoard(createBoardInput: $createBoardInput) {\n            _id\n            writer\n            title\n            contents\n            likeCount\n            dislikeCount\n            createdAt\n            youtubeUrl\n            boardAddress {\n                zipcode\n                address\n                addressDetail\n            }\n            images\n            createdAt\n        }\n    }\n": types.CreateBoardDocument,
    "\n    mutation updateBoard($boardId: ID!, $password: String, $updateBoardInput: UpdateBoardInput!) {\n        updateBoard(boardId: $boardId, password: $password, updateBoardInput: $updateBoardInput) {\n            _id\n            writer\n            title\n            contents\n            likeCount\n            dislikeCount\n            createdAt\n            youtubeUrl\n            boardAddress {\n                zipcode\n                address\n                addressDetail\n            }\n            images\n            createdAt\n        }\n    }\n": types.UpdateBoardDocument,
    "\n    mutation uploadFile($file: Upload!) {\n        uploadFile(file: $file) {\n            _id\n            url\n            size\n        }\n    }\n": types.UploadFileDocument,
    "\n    query fetchTravelproductsIPicked($search: String, $page: Int) {\n        fetchTravelproductsIPicked(search: $search, page: $page) {\n            _id\n            name\n            price\n            seller {\n                name\n            }\n            createdAt\n        }\n    }\n": types.FetchTravelproductsIPickedDocument,
    "\n    query fetchTravelproductsISold($page: Int) {\n        fetchTravelproductsISold(page: $page) {\n            _id\n            name\n            price\n            createdAt\n            soldAt\n        }\n    }\n": types.FetchTravelproductsISoldDocument,
    "\n    mutation resetUserPassword($password: String!) {\n        resetUserPassword(password: $password)\n    }\n": types.ResetUserPasswordDocument,
    "\n    query fetchPointTransactionsOfBuying($search: String, $page: Int) {\n        fetchPointTransactionsOfBuying(search: $search, page: $page) {\n            createdAt\n            travelproduct {\n                name\n                # seller {\n                #     name\n                # }\n            }\n            amount\n            balance\n        }\n    }\n": types.FetchPointTransactionsOfBuyingDocument,
    "\n    query fetchPointTransactionsOfSelling($search: String, $page: Int) {\n        fetchPointTransactionsOfSelling(search: $search, page: $page) {\n            createdAt\n            travelproduct {\n                name\n            }\n            amount\n            balance\n        }\n    }\n": types.FetchPointTransactionsOfSellingDocument,
    "\n    query fetchTravelproductsOfTheBest {\n        fetchTravelproductsOfTheBest {\n            _id\n            name\n            contents\n            price\n            pickedCount\n            images\n            soldAt\n        }\n    }\n": types.FetchTravelproductsOfTheBestDocument,
    "\n    mutation toggleTravelproductPick($travelproductId: ID!) {\n        toggleTravelproductPick(travelproductId: $travelproductId)\n    }\n": types.ToggleTravelproductPickDocument,
    "\n    mutation createPointTransactionOfBuyingAndSelling($useritemId: ID!) {\n        createPointTransactionOfBuyingAndSelling(useritemId: $useritemId) {\n            _id\n            name\n            remarks\n            contents\n            price\n            tags\n            images\n            pickedCount\n            travelproductAddress {\n                zipcode\n                address\n                addressDetail\n                lat\n                lng\n                # createdAt\n                # updatedAt\n            }\n            createdAt\n            updatedAt\n        }\n    }\n": types.CreatePointTransactionOfBuyingAndSellingDocument,
    "\n    mutation deleteTravelproduct($travelproductId: ID!) {\n        deleteTravelproduct(travelproductId: $travelproductId)\n    }\n": types.DeleteTravelproductDocument,
    "\n    mutation deleteTravelproductQuestion($travelproductQuestionId: ID!) {\n        deleteTravelproductQuestion(travelproductQuestionId: $travelproductQuestionId)\n    }\n": types.DeleteTravelproductQuestionDocument,
    "\n    query fetchTravelproductQuestions($travelproductId: ID!) {\n        fetchTravelproductQuestions(travelproductId: $travelproductId) {\n            _id\n            contents\n            user {\n                _id\n                email\n                name\n                createdAt\n                updatedAt\n            }\n            createdAt\n            updatedAt\n        }\n    }\n": types.FetchTravelproductQuestionsDocument,
    "\n    mutation deleteTravelproductQuestionAnswer($travelproductQuestionAnswerId: ID!) {\n        deleteTravelproductQuestionAnswer(\n            travelproductQuestionAnswerId: $travelproductQuestionAnswerId\n        )\n    }\n": types.DeleteTravelproductQuestionAnswerDocument,
    "\n    query fetchTravelproductQuestionAnswers($travelproductQuestionId: ID!) {\n        fetchTravelproductQuestionAnswers(travelproductQuestionId: $travelproductQuestionId) {\n            _id\n            contents\n            user {\n                _id\n                name\n                createdAt\n                updatedAt\n            }\n            createdAt\n            updatedAt\n        }\n    }\n": types.FetchTravelproductQuestionAnswersDocument,
    "\n    mutation createTravelproductQuestion(\n        $travelproductId: ID!\n        $createTravelproductQuestionInput: CreateTravelproductQuestionInput!\n    ) {\n        createTravelproductQuestion(\n            travelproductId: $travelproductId\n            createTravelproductQuestionInput: $createTravelproductQuestionInput\n        ) {\n            _id\n            contents\n\n            user {\n                _id\n                email\n                name\n                createdAt\n                updatedAt\n            }\n            createdAt\n            updatedAt\n        }\n    }\n": types.CreateTravelproductQuestionDocument,
    "\n    query fetchTravelproductQuestions($travelproductId: ID!) {\n        fetchTravelproductQuestions(travelproductId: $travelproductId) {\n            _id\n            contents\n\n            user {\n                _id\n                email\n                name\n                createdAt\n                updatedAt\n            }\n            createdAt\n            updatedAt\n        }\n    }\n": types.FetchTravelproductQuestionsDocument,
    "\n    mutation createTravelproductQuestionAnswer(\n        $travelproductQuestionId: ID!\n        $createTravelproductQuestionAnswerInput: CreateTravelproductQuestionAnswerInput!\n    ) {\n        createTravelproductQuestionAnswer(\n            createTravelproductQuestionAnswerInput: $createTravelproductQuestionAnswerInput\n            travelproductQuestionId: $travelproductQuestionId\n        ) {\n            _id\n            contents\n\n            user {\n                _id\n                email\n                name\n                createdAt\n                updatedAt\n            }\n            createdAt\n            updatedAt\n        }\n    }\n": types.CreateTravelproductQuestionAnswerDocument,
    "\n    mutation updateTravelproductQuestion(\n        $updateTravelproductQuestionInput: UpdateTravelproductQuestionInput!\n        $travelproductQuestionId: ID!\n    ) {\n        updateTravelproductQuestion(\n            updateTravelproductQuestionInput: $updateTravelproductQuestionInput\n            travelproductQuestionId: $travelproductQuestionId\n        ) {\n            _id\n            contents\n            user {\n                _id\n                email\n                name\n                createdAt\n                updatedAt\n            }\n            createdAt\n            updatedAt\n        }\n    }\n": types.UpdateTravelproductQuestionDocument,
    "\n    mutation updateTravelproductQuestionAnswer(\n        $travelproductQuestionAnswerId: ID!\n        $updateTravelproductQuestionAnswerInput: UpdateTravelproductQuestionAnswerInput!\n    ) {\n        updateTravelproductQuestionAnswer(\n            travelproductQuestionAnswerId: $travelproductQuestionAnswerId\n            updateTravelproductQuestionAnswerInput: $updateTravelproductQuestionAnswerInput\n        ) {\n            _id\n            contents\n            user {\n                _id\n                name\n            }\n            createdAt\n            updatedAt\n        }\n    }\n": types.UpdateTravelproductQuestionAnswerDocument,
    "\n    query fetchTravelproducts($isSoldout: Boolean, $page: Int, $search: String) {\n        fetchTravelproducts(isSoldout: $isSoldout, page: $page, search: $search) {\n            _id\n            name\n            remarks\n            contents\n            price\n            tags\n            images\n            pickedCount\n            travelproductAddress {\n                zipcode\n                address\n                addressDetail\n                lat\n                lng\n            }\n            seller {\n                _id\n                email\n                name\n            }\n            soldAt\n            createdAt\n            updatedAt\n        }\n    }\n": types.FetchTravelproductsDocument,
    "\n    mutation createTravelproduct($createTravelproductInput: CreateTravelproductInput!) {\n        createTravelproduct(createTravelproductInput: $createTravelproductInput) {\n            _id\n            name\n            remarks\n            contents\n            price\n            tags\n            images\n            pickedCount\n            travelproductAddress {\n                zipcode\n                address\n                addressDetail\n                lat\n                lng\n            }\n            buyer {\n                _id\n                email\n                name\n            }\n            seller {\n                _id\n                email\n                name\n            }\n            soldAt\n            createdAt\n            updatedAt\n        }\n    }\n": types.CreateTravelproductDocument,
    "\n    mutation updateTravelproduct(\n        $updateTravelproductInput: UpdateTravelproductInput!\n        $travelproductId: ID!\n    ) {\n        updateTravelproduct(\n            updateTravelproductInput: $updateTravelproductInput\n            travelproductId: $travelproductId\n        ) {\n            _id\n            name\n            remarks\n            contents\n            price\n            tags\n            images\n            pickedCount\n            travelproductAddress {\n                zipcode\n                address\n                addressDetail\n                lat\n                lng\n            }\n            buyer {\n                _id\n                email\n                name\n            }\n            seller {\n                _id\n                email\n                name\n            }\n            soldAt\n            createdAt\n            updatedAt\n        }\n    }\n": types.UpdateTravelproductDocument,
    "\n    mutation loginUser($email: String!, $password: String!) {\n        loginUser(password: $password, email: $email) {\n            accessToken\n        }\n    }\n": types.LoginUserDocument,
    "\n    mutation createUser($email: String!, $password: String!, $name: String!) {\n        createUser(createUserInput: { email: $email, password: $password, name: $name }) {\n            _id\n            email\n            name\n            picture\n            userPoint {\n                amount\n            }\n            createdAt\n        }\n    }\n": types.CreateUserDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query fetchUserLoggedIn {\n        fetchUserLoggedIn {\n            _id\n            email\n            name\n            userPoint {\n                amount\n            }\n        }\n    }\n"): (typeof documents)["\n    query fetchUserLoggedIn {\n        fetchUserLoggedIn {\n            _id\n            email\n            name\n            userPoint {\n                amount\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query fetchTravelproduct($travelproductId: ID!) {\n        fetchTravelproduct(travelproductId: $travelproductId) {\n            _id\n            name\n            remarks\n            contents\n            price\n            tags\n            images\n            pickedCount\n            travelproductAddress {\n                zipcode\n                address\n                addressDetail\n                lat\n                lng\n            }\n            buyer {\n                _id\n                email\n                name\n            }\n            seller {\n                _id\n                email\n                name\n            }\n            soldAt\n            createdAt\n            updatedAt\n        }\n    }\n"): (typeof documents)["\n    query fetchTravelproduct($travelproductId: ID!) {\n        fetchTravelproduct(travelproductId: $travelproductId) {\n            _id\n            name\n            remarks\n            contents\n            price\n            tags\n            images\n            pickedCount\n            travelproductAddress {\n                zipcode\n                address\n                addressDetail\n                lat\n                lng\n            }\n            buyer {\n                _id\n                email\n                name\n            }\n            seller {\n                _id\n                email\n                name\n            }\n            soldAt\n            createdAt\n            updatedAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation createPointTransactionOfLoading($paymentId: ID!) {\n        createPointTransactionOfLoading(paymentId: $paymentId) {\n            _id\n            amount\n            status\n            statusDetail\n            createdAt\n            updatedAt\n        }\n    }\n"): (typeof documents)["\n    mutation createPointTransactionOfLoading($paymentId: ID!) {\n        createPointTransactionOfLoading(paymentId: $paymentId) {\n            _id\n            amount\n            status\n            statusDetail\n            createdAt\n            updatedAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query fetchPointTransactions($search: String, $page: Int) {\n        fetchPointTransactions(search: $search, page: $page) {\n            _id\n            createdAt\n            status\n            amount\n            balance\n        }\n    }\n"): (typeof documents)["\n    query fetchPointTransactions($search: String, $page: Int) {\n        fetchPointTransactions(search: $search, page: $page) {\n            _id\n            createdAt\n            status\n            amount\n            balance\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query fetchPointTransactionsOfLoading($search: String, $page: Int) {\n        fetchPointTransactionsOfLoading(search: $search, page: $page) {\n            createdAt\n            impUid\n            amount\n            balance\n        }\n    }\n"): (typeof documents)["\n    query fetchPointTransactionsOfLoading($search: String, $page: Int) {\n        fetchPointTransactionsOfLoading(search: $search, page: $page) {\n            createdAt\n            impUid\n            amount\n            balance\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation logoutUser {\n        logoutUser\n    }\n"): (typeof documents)["\n    mutation logoutUser {\n        logoutUser\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation restoreAccessToken {\n        restoreAccessToken {\n            accessToken\n        }\n    }\n"): (typeof documents)["\n    mutation restoreAccessToken {\n        restoreAccessToken {\n            accessToken\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation deleteBoardComment($password: String, $boardCommentId: ID!) {\n        deleteBoardComment(password: $password, boardCommentId: $boardCommentId)\n    }\n"): (typeof documents)["\n    mutation deleteBoardComment($password: String, $boardCommentId: ID!) {\n        deleteBoardComment(password: $password, boardCommentId: $boardCommentId)\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query fetchBoardComments($boardId: ID!, $page: Int) {\n        fetchBoardComments(boardId: $boardId, page: $page) {\n            _id\n            writer\n            contents\n            rating\n            createdAt\n            user {\n                _id\n            }\n        }\n    }\n"): (typeof documents)["\n    query fetchBoardComments($boardId: ID!, $page: Int) {\n        fetchBoardComments(boardId: $boardId, page: $page) {\n            _id\n            writer\n            contents\n            rating\n            createdAt\n            user {\n                _id\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation createBoardComment($createBoardCommentInput: CreateBoardCommentInput!, $boardId: ID!) {\n        createBoardComment(createBoardCommentInput: $createBoardCommentInput, boardId: $boardId) {\n            _id\n            writer\n            contents\n            rating\n        }\n    }\n"): (typeof documents)["\n    mutation createBoardComment($createBoardCommentInput: CreateBoardCommentInput!, $boardId: ID!) {\n        createBoardComment(createBoardCommentInput: $createBoardCommentInput, boardId: $boardId) {\n            _id\n            writer\n            contents\n            rating\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation updateBoardComment(\n        $updateBoardCommentInput: UpdateBoardCommentInput!\n        $password: String\n        $boardCommentId: ID!\n    ) {\n        updateBoardComment(\n            updateBoardCommentInput: $updateBoardCommentInput\n            password: $password\n            boardCommentId: $boardCommentId\n        ) {\n            _id\n            writer\n            contents\n            rating\n            updatedAt\n        }\n    }\n"): (typeof documents)["\n    mutation updateBoardComment(\n        $updateBoardCommentInput: UpdateBoardCommentInput!\n        $password: String\n        $boardCommentId: ID!\n    ) {\n        updateBoardComment(\n            updateBoardCommentInput: $updateBoardCommentInput\n            password: $password\n            boardCommentId: $boardCommentId\n        ) {\n            _id\n            writer\n            contents\n            rating\n            updatedAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query fetchBoard($boardId: ID!) {\n        fetchBoard(boardId: $boardId) {\n            _id\n            writer\n            title\n            contents\n            likeCount\n            dislikeCount\n            createdAt\n            youtubeUrl\n            boardAddress {\n                zipcode\n                address\n                addressDetail\n            }\n            images\n            createdAt\n            user {\n                _id\n            }\n        }\n    }\n"): (typeof documents)["\n    query fetchBoard($boardId: ID!) {\n        fetchBoard(boardId: $boardId) {\n            _id\n            writer\n            title\n            contents\n            likeCount\n            dislikeCount\n            createdAt\n            youtubeUrl\n            boardAddress {\n                zipcode\n                address\n                addressDetail\n            }\n            images\n            createdAt\n            user {\n                _id\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation likeBoard($boardId: ID!) {\n        likeBoard(boardId: $boardId)\n    }\n"): (typeof documents)["\n    mutation likeBoard($boardId: ID!) {\n        likeBoard(boardId: $boardId)\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation dislikeBoard($boardId: ID!) {\n        dislikeBoard(boardId: $boardId)\n    }\n"): (typeof documents)["\n    mutation dislikeBoard($boardId: ID!) {\n        dislikeBoard(boardId: $boardId)\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query fetchBoards($page: Int, $search: String, $endDate: DateTime, $startDate: DateTime) {\n        fetchBoards(page: $page, search: $search, endDate: $endDate, startDate: $startDate) {\n            _id\n            writer\n            title\n            contents\n            youtubeUrl\n            likeCount\n            dislikeCount\n            boardAddress {\n                zipcode\n                address\n                addressDetail\n            }\n            createdAt\n            images\n        }\n    }\n"): (typeof documents)["\n    query fetchBoards($page: Int, $search: String, $endDate: DateTime, $startDate: DateTime) {\n        fetchBoards(page: $page, search: $search, endDate: $endDate, startDate: $startDate) {\n            _id\n            writer\n            title\n            contents\n            youtubeUrl\n            likeCount\n            dislikeCount\n            boardAddress {\n                zipcode\n                address\n                addressDetail\n            }\n            createdAt\n            images\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation deleteBoard($boardId: ID!) {\n        deleteBoard(boardId: $boardId)\n    }\n"): (typeof documents)["\n    mutation deleteBoard($boardId: ID!) {\n        deleteBoard(boardId: $boardId)\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query fetchBoardsCount($search: String, $startDate: DateTime, $endDate: DateTime) {\n        fetchBoardsCount(search: $search, startDate: $startDate, endDate: $endDate)\n    }\n"): (typeof documents)["\n    query fetchBoardsCount($search: String, $startDate: DateTime, $endDate: DateTime) {\n        fetchBoardsCount(search: $search, startDate: $startDate, endDate: $endDate)\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation createBoard($createBoardInput: CreateBoardInput!) {\n        createBoard(createBoardInput: $createBoardInput) {\n            _id\n            writer\n            title\n            contents\n            likeCount\n            dislikeCount\n            createdAt\n            youtubeUrl\n            boardAddress {\n                zipcode\n                address\n                addressDetail\n            }\n            images\n            createdAt\n        }\n    }\n"): (typeof documents)["\n    mutation createBoard($createBoardInput: CreateBoardInput!) {\n        createBoard(createBoardInput: $createBoardInput) {\n            _id\n            writer\n            title\n            contents\n            likeCount\n            dislikeCount\n            createdAt\n            youtubeUrl\n            boardAddress {\n                zipcode\n                address\n                addressDetail\n            }\n            images\n            createdAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation updateBoard($boardId: ID!, $password: String, $updateBoardInput: UpdateBoardInput!) {\n        updateBoard(boardId: $boardId, password: $password, updateBoardInput: $updateBoardInput) {\n            _id\n            writer\n            title\n            contents\n            likeCount\n            dislikeCount\n            createdAt\n            youtubeUrl\n            boardAddress {\n                zipcode\n                address\n                addressDetail\n            }\n            images\n            createdAt\n        }\n    }\n"): (typeof documents)["\n    mutation updateBoard($boardId: ID!, $password: String, $updateBoardInput: UpdateBoardInput!) {\n        updateBoard(boardId: $boardId, password: $password, updateBoardInput: $updateBoardInput) {\n            _id\n            writer\n            title\n            contents\n            likeCount\n            dislikeCount\n            createdAt\n            youtubeUrl\n            boardAddress {\n                zipcode\n                address\n                addressDetail\n            }\n            images\n            createdAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation uploadFile($file: Upload!) {\n        uploadFile(file: $file) {\n            _id\n            url\n            size\n        }\n    }\n"): (typeof documents)["\n    mutation uploadFile($file: Upload!) {\n        uploadFile(file: $file) {\n            _id\n            url\n            size\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query fetchTravelproductsIPicked($search: String, $page: Int) {\n        fetchTravelproductsIPicked(search: $search, page: $page) {\n            _id\n            name\n            price\n            seller {\n                name\n            }\n            createdAt\n        }\n    }\n"): (typeof documents)["\n    query fetchTravelproductsIPicked($search: String, $page: Int) {\n        fetchTravelproductsIPicked(search: $search, page: $page) {\n            _id\n            name\n            price\n            seller {\n                name\n            }\n            createdAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query fetchTravelproductsISold($page: Int) {\n        fetchTravelproductsISold(page: $page) {\n            _id\n            name\n            price\n            createdAt\n            soldAt\n        }\n    }\n"): (typeof documents)["\n    query fetchTravelproductsISold($page: Int) {\n        fetchTravelproductsISold(page: $page) {\n            _id\n            name\n            price\n            createdAt\n            soldAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation resetUserPassword($password: String!) {\n        resetUserPassword(password: $password)\n    }\n"): (typeof documents)["\n    mutation resetUserPassword($password: String!) {\n        resetUserPassword(password: $password)\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query fetchPointTransactionsOfBuying($search: String, $page: Int) {\n        fetchPointTransactionsOfBuying(search: $search, page: $page) {\n            createdAt\n            travelproduct {\n                name\n                # seller {\n                #     name\n                # }\n            }\n            amount\n            balance\n        }\n    }\n"): (typeof documents)["\n    query fetchPointTransactionsOfBuying($search: String, $page: Int) {\n        fetchPointTransactionsOfBuying(search: $search, page: $page) {\n            createdAt\n            travelproduct {\n                name\n                # seller {\n                #     name\n                # }\n            }\n            amount\n            balance\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query fetchPointTransactionsOfSelling($search: String, $page: Int) {\n        fetchPointTransactionsOfSelling(search: $search, page: $page) {\n            createdAt\n            travelproduct {\n                name\n            }\n            amount\n            balance\n        }\n    }\n"): (typeof documents)["\n    query fetchPointTransactionsOfSelling($search: String, $page: Int) {\n        fetchPointTransactionsOfSelling(search: $search, page: $page) {\n            createdAt\n            travelproduct {\n                name\n            }\n            amount\n            balance\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query fetchTravelproductsOfTheBest {\n        fetchTravelproductsOfTheBest {\n            _id\n            name\n            contents\n            price\n            pickedCount\n            images\n            soldAt\n        }\n    }\n"): (typeof documents)["\n    query fetchTravelproductsOfTheBest {\n        fetchTravelproductsOfTheBest {\n            _id\n            name\n            contents\n            price\n            pickedCount\n            images\n            soldAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation toggleTravelproductPick($travelproductId: ID!) {\n        toggleTravelproductPick(travelproductId: $travelproductId)\n    }\n"): (typeof documents)["\n    mutation toggleTravelproductPick($travelproductId: ID!) {\n        toggleTravelproductPick(travelproductId: $travelproductId)\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation createPointTransactionOfBuyingAndSelling($useritemId: ID!) {\n        createPointTransactionOfBuyingAndSelling(useritemId: $useritemId) {\n            _id\n            name\n            remarks\n            contents\n            price\n            tags\n            images\n            pickedCount\n            travelproductAddress {\n                zipcode\n                address\n                addressDetail\n                lat\n                lng\n                # createdAt\n                # updatedAt\n            }\n            createdAt\n            updatedAt\n        }\n    }\n"): (typeof documents)["\n    mutation createPointTransactionOfBuyingAndSelling($useritemId: ID!) {\n        createPointTransactionOfBuyingAndSelling(useritemId: $useritemId) {\n            _id\n            name\n            remarks\n            contents\n            price\n            tags\n            images\n            pickedCount\n            travelproductAddress {\n                zipcode\n                address\n                addressDetail\n                lat\n                lng\n                # createdAt\n                # updatedAt\n            }\n            createdAt\n            updatedAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation deleteTravelproduct($travelproductId: ID!) {\n        deleteTravelproduct(travelproductId: $travelproductId)\n    }\n"): (typeof documents)["\n    mutation deleteTravelproduct($travelproductId: ID!) {\n        deleteTravelproduct(travelproductId: $travelproductId)\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation deleteTravelproductQuestion($travelproductQuestionId: ID!) {\n        deleteTravelproductQuestion(travelproductQuestionId: $travelproductQuestionId)\n    }\n"): (typeof documents)["\n    mutation deleteTravelproductQuestion($travelproductQuestionId: ID!) {\n        deleteTravelproductQuestion(travelproductQuestionId: $travelproductQuestionId)\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query fetchTravelproductQuestions($travelproductId: ID!) {\n        fetchTravelproductQuestions(travelproductId: $travelproductId) {\n            _id\n            contents\n            user {\n                _id\n                email\n                name\n                createdAt\n                updatedAt\n            }\n            createdAt\n            updatedAt\n        }\n    }\n"): (typeof documents)["\n    query fetchTravelproductQuestions($travelproductId: ID!) {\n        fetchTravelproductQuestions(travelproductId: $travelproductId) {\n            _id\n            contents\n            user {\n                _id\n                email\n                name\n                createdAt\n                updatedAt\n            }\n            createdAt\n            updatedAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation deleteTravelproductQuestionAnswer($travelproductQuestionAnswerId: ID!) {\n        deleteTravelproductQuestionAnswer(\n            travelproductQuestionAnswerId: $travelproductQuestionAnswerId\n        )\n    }\n"): (typeof documents)["\n    mutation deleteTravelproductQuestionAnswer($travelproductQuestionAnswerId: ID!) {\n        deleteTravelproductQuestionAnswer(\n            travelproductQuestionAnswerId: $travelproductQuestionAnswerId\n        )\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query fetchTravelproductQuestionAnswers($travelproductQuestionId: ID!) {\n        fetchTravelproductQuestionAnswers(travelproductQuestionId: $travelproductQuestionId) {\n            _id\n            contents\n            user {\n                _id\n                name\n                createdAt\n                updatedAt\n            }\n            createdAt\n            updatedAt\n        }\n    }\n"): (typeof documents)["\n    query fetchTravelproductQuestionAnswers($travelproductQuestionId: ID!) {\n        fetchTravelproductQuestionAnswers(travelproductQuestionId: $travelproductQuestionId) {\n            _id\n            contents\n            user {\n                _id\n                name\n                createdAt\n                updatedAt\n            }\n            createdAt\n            updatedAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation createTravelproductQuestion(\n        $travelproductId: ID!\n        $createTravelproductQuestionInput: CreateTravelproductQuestionInput!\n    ) {\n        createTravelproductQuestion(\n            travelproductId: $travelproductId\n            createTravelproductQuestionInput: $createTravelproductQuestionInput\n        ) {\n            _id\n            contents\n\n            user {\n                _id\n                email\n                name\n                createdAt\n                updatedAt\n            }\n            createdAt\n            updatedAt\n        }\n    }\n"): (typeof documents)["\n    mutation createTravelproductQuestion(\n        $travelproductId: ID!\n        $createTravelproductQuestionInput: CreateTravelproductQuestionInput!\n    ) {\n        createTravelproductQuestion(\n            travelproductId: $travelproductId\n            createTravelproductQuestionInput: $createTravelproductQuestionInput\n        ) {\n            _id\n            contents\n\n            user {\n                _id\n                email\n                name\n                createdAt\n                updatedAt\n            }\n            createdAt\n            updatedAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query fetchTravelproductQuestions($travelproductId: ID!) {\n        fetchTravelproductQuestions(travelproductId: $travelproductId) {\n            _id\n            contents\n\n            user {\n                _id\n                email\n                name\n                createdAt\n                updatedAt\n            }\n            createdAt\n            updatedAt\n        }\n    }\n"): (typeof documents)["\n    query fetchTravelproductQuestions($travelproductId: ID!) {\n        fetchTravelproductQuestions(travelproductId: $travelproductId) {\n            _id\n            contents\n\n            user {\n                _id\n                email\n                name\n                createdAt\n                updatedAt\n            }\n            createdAt\n            updatedAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation createTravelproductQuestionAnswer(\n        $travelproductQuestionId: ID!\n        $createTravelproductQuestionAnswerInput: CreateTravelproductQuestionAnswerInput!\n    ) {\n        createTravelproductQuestionAnswer(\n            createTravelproductQuestionAnswerInput: $createTravelproductQuestionAnswerInput\n            travelproductQuestionId: $travelproductQuestionId\n        ) {\n            _id\n            contents\n\n            user {\n                _id\n                email\n                name\n                createdAt\n                updatedAt\n            }\n            createdAt\n            updatedAt\n        }\n    }\n"): (typeof documents)["\n    mutation createTravelproductQuestionAnswer(\n        $travelproductQuestionId: ID!\n        $createTravelproductQuestionAnswerInput: CreateTravelproductQuestionAnswerInput!\n    ) {\n        createTravelproductQuestionAnswer(\n            createTravelproductQuestionAnswerInput: $createTravelproductQuestionAnswerInput\n            travelproductQuestionId: $travelproductQuestionId\n        ) {\n            _id\n            contents\n\n            user {\n                _id\n                email\n                name\n                createdAt\n                updatedAt\n            }\n            createdAt\n            updatedAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation updateTravelproductQuestion(\n        $updateTravelproductQuestionInput: UpdateTravelproductQuestionInput!\n        $travelproductQuestionId: ID!\n    ) {\n        updateTravelproductQuestion(\n            updateTravelproductQuestionInput: $updateTravelproductQuestionInput\n            travelproductQuestionId: $travelproductQuestionId\n        ) {\n            _id\n            contents\n            user {\n                _id\n                email\n                name\n                createdAt\n                updatedAt\n            }\n            createdAt\n            updatedAt\n        }\n    }\n"): (typeof documents)["\n    mutation updateTravelproductQuestion(\n        $updateTravelproductQuestionInput: UpdateTravelproductQuestionInput!\n        $travelproductQuestionId: ID!\n    ) {\n        updateTravelproductQuestion(\n            updateTravelproductQuestionInput: $updateTravelproductQuestionInput\n            travelproductQuestionId: $travelproductQuestionId\n        ) {\n            _id\n            contents\n            user {\n                _id\n                email\n                name\n                createdAt\n                updatedAt\n            }\n            createdAt\n            updatedAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation updateTravelproductQuestionAnswer(\n        $travelproductQuestionAnswerId: ID!\n        $updateTravelproductQuestionAnswerInput: UpdateTravelproductQuestionAnswerInput!\n    ) {\n        updateTravelproductQuestionAnswer(\n            travelproductQuestionAnswerId: $travelproductQuestionAnswerId\n            updateTravelproductQuestionAnswerInput: $updateTravelproductQuestionAnswerInput\n        ) {\n            _id\n            contents\n            user {\n                _id\n                name\n            }\n            createdAt\n            updatedAt\n        }\n    }\n"): (typeof documents)["\n    mutation updateTravelproductQuestionAnswer(\n        $travelproductQuestionAnswerId: ID!\n        $updateTravelproductQuestionAnswerInput: UpdateTravelproductQuestionAnswerInput!\n    ) {\n        updateTravelproductQuestionAnswer(\n            travelproductQuestionAnswerId: $travelproductQuestionAnswerId\n            updateTravelproductQuestionAnswerInput: $updateTravelproductQuestionAnswerInput\n        ) {\n            _id\n            contents\n            user {\n                _id\n                name\n            }\n            createdAt\n            updatedAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query fetchTravelproducts($isSoldout: Boolean, $page: Int, $search: String) {\n        fetchTravelproducts(isSoldout: $isSoldout, page: $page, search: $search) {\n            _id\n            name\n            remarks\n            contents\n            price\n            tags\n            images\n            pickedCount\n            travelproductAddress {\n                zipcode\n                address\n                addressDetail\n                lat\n                lng\n            }\n            seller {\n                _id\n                email\n                name\n            }\n            soldAt\n            createdAt\n            updatedAt\n        }\n    }\n"): (typeof documents)["\n    query fetchTravelproducts($isSoldout: Boolean, $page: Int, $search: String) {\n        fetchTravelproducts(isSoldout: $isSoldout, page: $page, search: $search) {\n            _id\n            name\n            remarks\n            contents\n            price\n            tags\n            images\n            pickedCount\n            travelproductAddress {\n                zipcode\n                address\n                addressDetail\n                lat\n                lng\n            }\n            seller {\n                _id\n                email\n                name\n            }\n            soldAt\n            createdAt\n            updatedAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation createTravelproduct($createTravelproductInput: CreateTravelproductInput!) {\n        createTravelproduct(createTravelproductInput: $createTravelproductInput) {\n            _id\n            name\n            remarks\n            contents\n            price\n            tags\n            images\n            pickedCount\n            travelproductAddress {\n                zipcode\n                address\n                addressDetail\n                lat\n                lng\n            }\n            buyer {\n                _id\n                email\n                name\n            }\n            seller {\n                _id\n                email\n                name\n            }\n            soldAt\n            createdAt\n            updatedAt\n        }\n    }\n"): (typeof documents)["\n    mutation createTravelproduct($createTravelproductInput: CreateTravelproductInput!) {\n        createTravelproduct(createTravelproductInput: $createTravelproductInput) {\n            _id\n            name\n            remarks\n            contents\n            price\n            tags\n            images\n            pickedCount\n            travelproductAddress {\n                zipcode\n                address\n                addressDetail\n                lat\n                lng\n            }\n            buyer {\n                _id\n                email\n                name\n            }\n            seller {\n                _id\n                email\n                name\n            }\n            soldAt\n            createdAt\n            updatedAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation updateTravelproduct(\n        $updateTravelproductInput: UpdateTravelproductInput!\n        $travelproductId: ID!\n    ) {\n        updateTravelproduct(\n            updateTravelproductInput: $updateTravelproductInput\n            travelproductId: $travelproductId\n        ) {\n            _id\n            name\n            remarks\n            contents\n            price\n            tags\n            images\n            pickedCount\n            travelproductAddress {\n                zipcode\n                address\n                addressDetail\n                lat\n                lng\n            }\n            buyer {\n                _id\n                email\n                name\n            }\n            seller {\n                _id\n                email\n                name\n            }\n            soldAt\n            createdAt\n            updatedAt\n        }\n    }\n"): (typeof documents)["\n    mutation updateTravelproduct(\n        $updateTravelproductInput: UpdateTravelproductInput!\n        $travelproductId: ID!\n    ) {\n        updateTravelproduct(\n            updateTravelproductInput: $updateTravelproductInput\n            travelproductId: $travelproductId\n        ) {\n            _id\n            name\n            remarks\n            contents\n            price\n            tags\n            images\n            pickedCount\n            travelproductAddress {\n                zipcode\n                address\n                addressDetail\n                lat\n                lng\n            }\n            buyer {\n                _id\n                email\n                name\n            }\n            seller {\n                _id\n                email\n                name\n            }\n            soldAt\n            createdAt\n            updatedAt\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation loginUser($email: String!, $password: String!) {\n        loginUser(password: $password, email: $email) {\n            accessToken\n        }\n    }\n"): (typeof documents)["\n    mutation loginUser($email: String!, $password: String!) {\n        loginUser(password: $password, email: $email) {\n            accessToken\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation createUser($email: String!, $password: String!, $name: String!) {\n        createUser(createUserInput: { email: $email, password: $password, name: $name }) {\n            _id\n            email\n            name\n            picture\n            userPoint {\n                amount\n            }\n            createdAt\n        }\n    }\n"): (typeof documents)["\n    mutation createUser($email: String!, $password: String!, $name: String!) {\n        createUser(createUserInput: { email: $email, password: $password, name: $name }) {\n            _id\n            email\n            name\n            picture\n            userPoint {\n                amount\n            }\n            createdAt\n        }\n    }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;